name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get
      
      - name: Update CocoaPods repository
        run: pod repo update
        working-directory: ios

      - name: Install CocoaPods dependencies
        run: pod install
        working-directory: ios

      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      - name: Create Payload directory
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: Move Runner.app to Payload
        run: mv Runner.app Payload/
        working-directory: build/ios/iphoneos

      - name: Zip the Payload directory into an IPA file
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
